### ISSUE TITLE
Testing the magic

### ISSUE THREAD

**Issue by ArnaudGastinel** [WildMoka/TestQA#1]
Magic create branches

**Comment by ArnaudGastinel** [comment]
Magic create branches

**Comment by ArnaudGastinel** [comment]
Magic create branches

**Comment by ArnaudGastinel** [comment]
Magic create branches

**Comment by ArnaudGastinel** [comment]
Magic create branches

**Comment by ArnaudGastinel** [comment]
Magic create branches on 'release'

**Comment by ArnaudGastinel** [comment]
Magic create branches on 'release'

**Comment by ArnaudGastinel** [comment]
Magic create branches on 'release'

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Branch QA-1 is created for repositories: TestRepo1

**Comment by ArnaudGastinel** [comment]
Magic create branches on 'release'

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Branch QA-1 from base branch: release was already created for repositories: TestRepo1

**Comment by ArnaudGastinel** [comment]
Magic create branches on 'release'

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Branch QA-1 from base branch 'release' was already created for repositories: TestRepo1

**Comment by ArnaudGastinel** [comment]
magic create pull request to 'release'

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL REQUEST TO 'release'

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL REQUEST TO 'release'

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL REQUEST TO 'release'

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/warning.png) Pull request creation is not needed.

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL REQUEST TO 'release'

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pull request created on QA-1 for repositories: TestRepo1.

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL REQUEST TO 'master'

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL REQUEST TO 'master'

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/warning.png) Pull request creation is not needed.

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
https://jenkins.wildmoka.com:5043/job/DevProcessAutomationHook/43666/

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL REQUEST TO 'master'

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pull request created on QA-1 for repositories: TestRepo1.

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
https://jenkins.wildmoka.com:5043/job/DevProcessAutomationHook/43672/

**Comment by ArnaudGastinel** [comment]
magic create pull request

**Comment by ArnaudGastinel** [comment]
magic create branches

**Comment by ArnaudGastinel** [comment]
magic create branches

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Branch QA-1 from base branch 'master' was already created for repositories: TestRepo1

**Comment by ArnaudGastinel** [comment]
Magic create pull request

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pull request created on QA-1 for repositories: TestRepo1.

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
https://jenkins.wildmoka.com:5043/job/DevProcessAutomationHook/43692/

**Comment by ArnaudGastinel** [comment]
magic create pull request to releaseqasdad

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pull request created on QA-1 for repositories: TestRepo1.

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
https://jenkins.wildmoka.com:5043/job/DevProcessAutomationHook/43707/

**Comment by ArnaudGastinel** [comment]
magic create pull request to 'rearadasdladasd'

**Comment by ArnaudGastinel** [comment]
magic create pull request to 'rearadasdladasd'

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/warning.png) Pull request creation is not needed.

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Errors during Magic process: 
 Cannot compare branches QA-1 and rearadasdladasd.
Cannot continue to create pull requests. 
Message: Not Found

**Comment by ArnaudGastinel** [comment]
magic create pull request to 'rearadasdladasd'

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/warning.png) Pull request creation is not needed.

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Errors during Magic process: 
 Cannot compare branches QA-1 and rearadasdladasd.
Cannot continue to create pull requests. 
Message: Not Found

**Comment by ArnaudGastinel** [comment]
magic create pull request to 'wrongBranch'

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Errors during Magic process: 
 Cannot compare branches QA-1 and wrongBranch.
Cannot continue to create pull requests. 
Message: Not Found

**Comment by ArnaudGastinel** [comment]
magic delete branches

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Branch QA-1 deleted for repositories: TestRepo1

**Comment by ArnaudGastinel** [comment]
magic create branches from 'toto'

**Comment by ArnaudGastinel** [comment]
magic create branches from 'toto'

**Comment by ArnaudGastinel** [comment]
magic create branches from 'toto'

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Errors during Magic process: 
 Cannot get the head of branch toto. Message: {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Not Found'}

**Comment by ArnaudGastinel** [comment]
magic create branches from toto tatra

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Branch QA-1 from base branch 'master' is created for repositories: TestRepo1

**Comment by ArnaudGastinel** [comment]
magic delete branches

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Branch QA-1 deleted for repositories: TestRepo1

**Comment by ArnaudGastinel** [comment]
magic create branches from toto tatra

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Errors during Magic process: 
 Cannot get the head of branch tatra. Message: Not Found

**Comment by ArnaudGastinel** [comment]
magic create branches from toto tatra

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Errors during Magic process: 
 Cannot get the head of branch tatra. Message: Not Found

**Comment by ArnaudGastinel** [comment]
magic create branches from toto tatra

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Errors during Magic process: 
 Cannot get the head of branch tatra. Message: Not Found

**Comment by ArnaudGastinel** [comment]
magic create branches from toto tatra

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Errors during Magic process: 
 Cannot get the head of branch toto. Message: Not Found

**Comment by ArnaudGastinel** [comment]
magic create branches from master

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Branch QA-1 from base branch 'master' is created for repositories: TestRepo1

**Comment by ArnaudGastinel** [comment]
magic create pull request

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/warning.png) Pull request creation is not needed.

**Comment by ArnaudGastinel** [comment]
magic create pull request

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/warning.png) Pull request creation is not needed.

**Comment by ArnaudGastinel** [comment]
magic create pull request

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pull request created on QA-1 for repositories: TestRepo1.

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
https://jenkins.wildmoka.com:5043/job/DevProcessAutomationHook/44756/

**Comment by ArnaudGastinel** [comment]
magic create pull request to release

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pull request created on QA-1 for repositories: TestRepo1.

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Pull request auto-created for repository: TestRepo2

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
https://jenkins.wildmoka.com:5043/job/DevProcessAutomationHook/44766/

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
https://jenkins.wildmoka.com:5043/job/DevProcessAutomationHook/44768/

**Comment by ArnaudGastinel** [comment]
magic create pull request

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pull request created on QA-1 for repositories: TestRepo1,TestRepo2.

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
https://jenkins.wildmoka.com:5043/job/DevProcessAutomationHook/44775/

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
https://jenkins.wildmoka.com:5043/job/DevProcessAutomationHook/44777/

**Comment by ArnaudGastinel** [comment]
magic create pull request from release

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pull request created on QA-1 for repositories: TestRepo1,TestRepo2.

**Comment by ArnaudGastinel** [comment]
magic merge

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Branch QA-1 on TestRepo1 doesn't have a successful build state
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Pull request 'AUTO Pull request created for issue #QA-1' on TestRepo1 has conflict with master
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Branch QA-1 on TestRepo2 doesn't have a successful build state
Merge aborted.

**Comment by ArnaudGastinel** [comment]
magic merge

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Branch QA-1 on TestRepo1 doesn't have a successful build state
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Pull request 'AUTO Pull request created for issue #QA-1' on TestRepo1 has conflict with release
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Branch QA-1 on TestRepo2 doesn't have a successful build state
Merge aborted.

**Comment by ArnaudGastinel** [comment]
magic create pull request to master

**Comment by ArnaudGastinel** [comment]
magic create pull request to master

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/warning.png) Pull request creation is not possible due to existing pull request with different base branch.

**Comment by AutomationWildMoka** [comment]
Magic rebuild
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) master has changed from issue 70
Merge master into QA-1 for repositories TestRepo1.

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Pull request 'AUTO Pull request created for issue #QA-1' on TestRepo1 has a conflict with release -> no build will be done until you resolve the conflict

**Comment by AutomationWildMoka** [comment]
Magic rebuild
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) master has changed from issue 70
Merge master into QA-1 for repositories TestRepo1.

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Pull request 'AUTO Pull request created for issue #QA-1' on TestRepo1 has a conflict with release -> no build will be done until you resolve the conflict
