### ISSUE TITLE
Testing QA-807

### ISSUE THREAD

**Issue by ArnaudGastinel** [WildMoka/TestQA#2]

**Comment by ArnaudGastinel** [comment]
Magic create branches

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Branch QA-2 from base branch master is created for repositories: TestRepo1,TestRepo2

**Comment by ArnaudGastinel** [comment]
magic create pull request

**Comment by ArnaudGastinel** [comment]
magic create pull request

**Comment by ArnaudGastinel** [comment]
magic create pull request

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pull request created on QA-2 for repositories: TestRepo1.

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Pull request auto-created for repository: TestRepo2

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
https://jenkins.wildmoka.com:5043/job/DevProcessAutomationHook/126952/

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Pull request closed on QA-2 for repositories: TestRepo1.
