### ISSUE TITLE
Testing QA-804

### ISSUE THREAD

**Issue by chioubaca** [WildMoka/TestQA#3]
MAGIC CREATE BRANCHES

**Comment by chioubaca** [comment]
MAGIC CREATE BRANCHES on dev

**Comment by chioubaca** [comment]
MAGIC CREATE BRANCHES

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Branch QA-3 from base branch master is created for repositories: TestRepo1,TestRepo2

**Comment by chioubaca** [comment]
MAGIC CREATE PULL REQUEST

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/warning.png) Pull request creation is not needed.

**Comment by chioubaca** [comment]
MAGIC DELETE BRANCHES

**Comment by chioubaca** [comment]
MAGIC DELETE BRANCHES

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Branch QA-3 deleted for repositories: TestRepo2

**Comment by chioubaca** [comment]
MAGIC CREATE BRANCHES

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Branch QA-3 from base branch master is created for repositories: TestRepo1,TestRepo2

**Comment by chioubaca** [comment]
MAGIC CREATE PULL REQUEST

**Comment by chioubaca** [comment]
MAGIC CREATE PULL REQUEST

**Comment by chioubaca** [comment]
MAGIC DELETE BRANCHES

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Branch QA-3 deleted for repositories: TestRepo1,TestRepo2

**Comment by chioubaca** [comment]
MAGIC CREATE BRANCHES

**Comment by chioubaca** [comment]
MAGIC CREATE BRANCHES

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Branch QA-3 from base branch master is created for repositories: TestRepo1,TestRepo2

**Comment by chioubaca** [comment]
MAGIC CREATE PULL REQUEST

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pull request created on QA-3 for repositories: TestRepo1.

**Comment by chioubaca** [comment]
MAGIC REBUILD

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) BUILD in progress
 Modified Repositories: TestRepo1

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Build finished with status: success.
https://jenkins.wildmoka.com:5043/job/DevProcessAutomationBuild/2429/

**Comment by AutomationWildMoka** [comment]
Magic rebuild
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) master has changed from issue 70
Merge master into QA-3 for repositories TestRepo1.

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Pull request 'AUTO Pull request created for issue #QA-3' on TestRepo1 has a conflict with master -> no build will be done until you resolve the conflict

**Comment by AutomationWildMoka** [comment]
Magic rebuild
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) master has changed from issue 70
Merge master into QA-3 for repositories TestRepo1.

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Pull request 'AUTO Pull request created for issue #QA-3' on TestRepo1 has a conflict with master -> no build will be done until you resolve the conflict
