### ISSUE TITLE
Test 1751

### ISSUE THREAD

**Issue by JudithDu** [WildMoka/TestQA#71]

**Comment by JudithDu** [comment]
magic create branches on integration

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Errors during Magic process: 
 Cannot get the head of branch integration. Message: Not Found

**Comment by JudithDu** [comment]
magic create branches on release

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Branch QA-71 from base branch release is created for repositories: TestRepo1,TestRepo2

**Comment by JudithDu** [comment]
magic create pull request

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Errors during Magic process: 
 You MUST specify the base branch (master or release).

**Comment by JudithDu** [comment]
magic create pull request on release

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/warning.png) Pull request creation is not needed.

**Comment by JudithDu** [comment]
magic create pull request on release

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pullrequests created for QA-71:
https://github.com/WildMoka/TestRepo1/pull/17 on TestRepo1.

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) BUILD in progress
 Modified Repositories: TestRepo1

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Build finished with status: success.
http://192.168.84.170:8080/job/DevProcessAutomationBuild/8864/

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Pull request https://github.com/WildMoka/TestRepo1/pull/18 auto-created for repository: TestRepo1

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/error.png) Pull request 'AUTO Pull request created for issue #QA-71' on TestRepo1 has a conflict with master -> no build will be done until you resolve the conflict

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
http://192.168.84.170:8080/job/DevProcessAutomationHook/184945/

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Pull request closed on QA-71 for repositories: TestRepo1.

**Comment by JudithDu** [comment]
magic create pull request on release

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pullrequests created for QA-71:
https://github.com/WildMoka/TestRepo1/pull/19 on TestRepo1
https://github.com/WildMoka/TestRepo2/pull/8 on TestRepo2.

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) BUILD in progress
 Modified Repositories: TestRepo1,TestRepo2

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Build finished with status: success.
http://192.168.84.170:8080/job/DevProcessAutomationBuild/8866/

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
http://192.168.84.170:8080/job/DevProcessAutomationHook/185327/

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Pull request closed on QA-71 for repositories: TestRepo2.

**Comment by AutomationWildMoka** [comment]
Pull request has been manually closed, closing automatically all opened pull requests. 
http://192.168.84.170:8080/job/DevProcessAutomationHook/185406/
