### ISSUE TITLE
Test 1751-2

### ISSUE THREAD

**Issue by JudithDu** [WildMoka/TestQA#72]

**Comment by JudithDu** [comment]
magic create branches on release

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Branch QA-72 from base branch release is created for repositories: TestRepo1,TestRepo2

**Comment by JudithDu** [comment]
magic create pull request on release

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Pullrequests created for QA-72:
https://github.com/WildMoka/TestRepo1/pull/20 on TestRepo1.

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) BUILD in progress
 Modified Repositories: TestRepo1

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Build finished with status: success.
http://192.168.84.170:8080/job/DevProcessAutomationBuild/8889/

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Pull request https://github.com/WildMoka/TestRepo2/pull/10 auto-created for repository: TestRepo2

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) BUILD in progress
 Modified Repositories: TestRepo1,TestRepo2

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Build finished with status: success.
http://192.168.84.170:8080/job/DevProcessAutomationBuild/8890/

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) Push on repository TestRepo1

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/info.png) BUILD in progress
 Modified Repositories: TestRepo1,TestRepo2

**Comment by AutomationWildMoka** [comment]
![GitHub Logo](http://tv3.wildmoka.com/static2/jenkins/success.png) Build finished with status: success.
http://192.168.84.170:8080/job/DevProcessAutomationBuild/8891/
